export default{
    menuData:[
        {
            name:"首页",
            path:"/admin/home",
            id:'0'
        },
        {
            name:"设置",
            path:"/admin/setting",
            id:'1'
        },
        {
            name:"用户管理",
            path:"/admin/user",
            id:'2',
            children:[
                {
                    name:"用户添加",
                    path:"/admin/user/add",
                    id:'20'
                },
                {
                    name:"管理员管理",
                    path:"/admin/user/root",
                    id:'21'
                }
            ]
        },
        {
            name:"图标展示",
            path:"/admin/echart",
            id:'3',
            children:[
                { 
                    name:"饼状图",
                    path:"/admin/echart/bin",
                    id:"30",
                    children:[
                        {
                            name:"饼状图1",
                            path:"/admin/echart/bin/one",
                             id:'300'
                        },
                        {
                            name:"饼状图2",
                            path:"/admin/echart/bin/two",
                            id:'301'
                        }
                    ]                    
                },
                {
                   name:"折线图",
                   path:"/admin/echart/line",
                   id:'31',
                   children:[
                       {
                           name:"折线图1",
                           path:"/admin/echart/line/one",
                           id:'312'
                       },
                       {
                           name:"折线图2",
                           path:"/admin/echart/line/two",
                           id:'313'
                       }
                   ] 
                }
            ]
        }
    ]
}